# These are supported funding model platforms
# Uncomment and fill in the ones you use

# github: Dardcor
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
buy_me_a_coffee: # your_username
# custom: ["https://www.dardcor.my.id/donate"]
